baseURL = "https://taehoon03.github.io/taehoon03.github.io/"
languagecode = "ko-kr"
title = "My-blog"
theme = "terminal"
paginate = 5

[params]
  contentTypeName = "posts"
  themeColor = "green"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = false

[languages]
  [languages.ko]
    title = "블로그 제목"
    subtitle = "보안 공부 기록"
    keywords = ""
    copyright = ""
    menuMore = "more"
    readMore = "더 읽기"
    readOtherPosts = "다른 글"
    newerPosts = "최신 글"
    olderPosts = "이전 글"

    [[languages.ko.menu.main]]
      identifier = "about"
      name = "about"
      url = "/about"

    [[languages.ko.menu.main]]
      identifier = "posts"
      name = "posts"
      url = "/posts"
